pipeline {
    agent none
    stages {
        stage('Run Tests') {
            parallel {
                stage('Windows') {
                    steps {
                        echo "run-tests.bat"
                    }
                    post {
                        always {
                            echo "stage windows"
                        }
                    }
                }
                stage('Linux') {
                    steps {
                        echo "Step test on linuc"
                    }
                    post {
                        always {
                            echo "stage linux"
                        }
                    }
                }
            }
        }
    }
}